app = "snowbattle"
primary_region = "nrt"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "2567"

[http_service]
  internal_port = 2567
  force_https = true
  auto_start_machines = true
  auto_stop_machines = "stop"
  min_machines_running = 1
  processes = ["app"]

  [[http_service.checks]]
    grace_period = "10s"
    interval = "15s"
    method = "GET"
    path = "/health"
    timeout = "5s"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512
